feat: add netmask
deepin-community/netmask pull request #1
Opened 2023-07-11 08:41 UTC by Udacv

Netmask helps determine network masks.

Log: add netmask
Issue: deepin-community/sig-deepin-sysdev-team#368

2023-07-11 08:59 UTC, UTsweetyfish requested changes
这个包是自行打包还是从 debian 来的？

如果是 debian 来的，debian/copyright 里面 debian/* 的 LGPL-3 以后怕是有问题

如果是自行打包的话，debian/changelog 里面版本号不应该上来就是 4？

2023-07-11 09:00 UTC, Udacv commented
> 这个包是自行打包还是从 debian 来的？
> 
> 如果是 debian 来的，debian/copyright 里面 debian/* 的 LGPL-3 以后怕是有问题
> 
> 如果是自行打包的话，debian/changelog 里面版本号不应该上来就是 4？

从debian来的，我修改一下

2023-07-11 09:00 UTC, Udacv commented
> 

所以copyright里面的应该写什么呢

2023-07-11 09:02 UTC, Udacv commented
> 

就复制原包中的debian/*部分的证书就可以么

2023-07-11 09:02 UTC, UTsweetyfish commented
> > 
> 
> 所以copyright里面的应该写什么呢

如果从 debian 来的时候完全没有修改的需求，则完全不动

如果有修改的需求，则作出修改然后 bump changelog。

copyright 通常不动。

2023-07-11 09:04 UTC, Udacv commented
> > > 
> > 
> > 
> > 所以copyright里面的应该写什么呢
> 
> 如果从 debian 来的时候完全没有修改的需求，则完全不动
> 
> 如果有修改的需求，则作出修改然后 bump changelog。
> 
> copyright 通常不动。

好的我去修改

2023-07-13 02:16 UTC, Udacv commented
@chenchongbiao

2023-07-13 02:19 UTC, UTsweetyfish commented
/approve

2023-07-13 02:20 UTC, merged